leftnav:
- identifier: external--236184328-1684163397789
  name: Introductory Programming Courses
  url: https://ocw.mit.edu/collections/introductory-programming/
  weight: 10
- identifier: external-1372501303-1685043003930
  name: Archived D-Space Course
  url: https://dspace.mit.edu/handle/1721.1/150601
  weight: 20
